### ISSUE TITLE
Click on node osm data sometimes does not show the correct feature.

### ISSUE THREAD

**Issue by homersimpsons** [maproulette/maproulette3#2452]
**Describe the bug**
When displaying OSM Data on the map, sometimes clicking on the data (feature, e.g.: node) does not display the correct information.

**Expected behavior**
Clicking on the data (feature) shows the correct information.

**To Reproduce**
1. Go to https://maproulette.org/challenge/11605/task/234514862
2. Click on "layer" icon on the map
3. Select a map feature (example OSM Data > Node)
4. Select the circled node on the map
5. See error: it displays informations about a way instead of the node

**Screenshots**
![image](https://github.com/user-attachments/assets/ea2fafb1-ad23-433c-9545-7597a35ac202)

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Firefox
- Version: 130.0.1

**Comment by mvexel** [comment]
I see this for the example task you provided:

<img width="844" alt="image" src="https://github.com/user-attachments/assets/81ede477-5cd1-4f44-a9e1-644d77befc40" />

<img width="844" alt="image" src="https://github.com/user-attachments/assets/fcaa4d05-3262-498f-98ff-5c91f0e36f56" />

Is it possible this was fixed in the meantime (since some time has passed since this was opened)?

@homersimpsons could you verify please?

**Comment by homersimpsons** [comment]
![image](https://github.com/user-attachments/assets/eba9e781-858c-427e-b20a-b63b7c00d5f5)

Looks like I still have the issue on Firefox.

**Comment by mvexel** [comment]
Okay - we are starting to figure it out:

<img width="699" alt="image" src="https://github.com/user-attachments/assets/9cd5ab64-f36a-474f-a560-d1aa39e1bda4" />

This is what I see when i just have NODES enabled in the OSM data - -the error you are seeing as well

When I also select ways, clicking on the same feature shows a different result:

<img width="699" alt="image" src="https://github.com/user-attachments/assets/a35ab11b-582c-490f-94a4-cebba6ea2185" />

We will look into this more
